name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: yarn ci
      env:
        CI: true
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.mo }} #required
        file: ./coverage/clover.xml
        flags: unittests
        fail_ci_if_error: true
