name: Publish CI

on:
  release:
    types: [created]
    tags:        
      - v*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo $NODE_AUTH_TOKEN >> .npmrc && echo echo $NODE_AUTH_TOKEN >> .yarnrc
      env:
        NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
    - run: yarn
    - run: yarn build:lib
    - name: Deploy core
      run: >
        PACKAGE_VERSION = echo $REF | grep ":v([0-9]\.?)*"
        (cd packages/core && yarn publish --access public --version $PACKAGE_VERSION)
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        REF: ${{github.ref}}
    - name: Deploy hooks
      run: >
        PACKAGE_VERSION = echo $REF | grep ":v([0-9]\.?)*"
        (cd packages/hooks && yarn publish --access public --version $PACKAGE_VERSION)
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        REF: ${{github.ref}}
